/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnwaelteRouteImport } from './routes/anwaelte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as FachgebieteRouteImport } from './routes/fachgebiete'
import { Route as FileuploadRouteImport } from './routes/fileupload'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KanzleiRouteImport } from './routes/kanzlei'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as RechnungRouteImport } from './routes/rechnung'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AngebotAnfordernIndexRouteImport } from './routes/angebot-anfordern.index'
import { Route as AngebotAnfordernDankeRouteImport } from './routes/angebot-anfordern.danke'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminEinstellungenRouteImport } from './routes/_authenticated/admin.einstellungen'
import { Route as AuthenticatedAdminManuellRouteImport } from './routes/_authenticated/admin.manuell'
import { Route as AuthenticatedAdminTrafficRouteImport } from './routes/_authenticated/admin.traffic'
import { Route as BelegPrintArtTokenRouteImport } from './routes/beleg-print.$art.$token'
import { Route as JuliAngeboteFilenameRouteImport } from './routes/juli.angebote.$filename'
import { Route as ApiPublicAdminSendInvoiceRouteImport } from './routes/api/public/admin/send-invoice'
import { Route as ApiPublicAdminSendManualInvoiceRouteImport } from './routes/api/public/admin/send-manual-invoice'
import { Route as ApiPublicAdminSendOfferRouteImport } from './routes/api/public/admin/send-offer'
import { Route as ApiPublicAdminSendPaymentConfirmationRouteImport } from './routes/api/public/admin/send-payment-confirmation'
import { Route as ApiPublicHooksAcceptOfferRouteImport } from './routes/api/public/hooks/accept-offer'
import { Route as ApiPublicHooksConfirmManualRouteImport } from './routes/api/public/hooks/confirm-manual'
import { Route as ApiPublicHooksMarkPaidRouteImport } from './routes/api/public/hooks/mark-paid'
import { Route as ApiPublicHooksSendScheduledOffersRouteImport } from './routes/api/public/hooks/send-scheduled-offers'
import { Route as ApiPublicHooksTrackRouteImport } from './routes/api/public/hooks/track'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnwaelteRoute = AnwaelteRouteImport.update({
  id: '/anwaelte',
  path: '/anwaelte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const FachgebieteRoute = FachgebieteRouteImport.update({
  id: '/fachgebiete',
  path: '/fachgebiete',
  getParentRoute: () => rootRouteImport,
} as any)
const FileuploadRoute = FileuploadRouteImport.update({
  id: '/fileupload',
  path: '/fileupload',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KanzleiRoute = KanzleiRouteImport.update({
  id: '/kanzlei',
  path: '/kanzlei',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnungRoute = RechnungRouteImport.update({
  id: '/rechnung',
  path: '/rechnung',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AngebotAnfordernIndexRoute = AngebotAnfordernIndexRouteImport.update({
  id: '/angebot-anfordern/',
  path: '/angebot-anfordern/',
  getParentRoute: () => rootRouteImport,
} as any)
const AngebotAnfordernDankeRoute = AngebotAnfordernDankeRouteImport.update({
  id: '/angebot-anfordern/danke',
  path: '/angebot-anfordern/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEinstellungenRoute =
  AuthenticatedAdminEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManuellRoute =
  AuthenticatedAdminManuellRouteImport.update({
    id: '/manuell',
    path: '/manuell',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTrafficRoute =
  AuthenticatedAdminTrafficRouteImport.update({
    id: '/traffic',
    path: '/traffic',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const BelegPrintArtTokenRoute = BelegPrintArtTokenRouteImport.update({
  id: '/beleg-print/$art/$token',
  path: '/beleg-print/$art/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JuliAngeboteFilenameRoute = JuliAngeboteFilenameRouteImport.update({
  id: '/juli/angebote/$filename',
  path: '/juli/angebote/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSendInvoiceRoute =
  ApiPublicAdminSendInvoiceRouteImport.update({
    id: '/api/public/admin/send-invoice',
    path: '/api/public/admin/send-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSendManualInvoiceRoute =
  ApiPublicAdminSendManualInvoiceRouteImport.update({
    id: '/api/public/admin/send-manual-invoice',
    path: '/api/public/admin/send-manual-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSendOfferRoute = ApiPublicAdminSendOfferRouteImport.update({
  id: '/api/public/admin/send-offer',
  path: '/api/public/admin/send-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminSendPaymentConfirmationRoute =
  ApiPublicAdminSendPaymentConfirmationRouteImport.update({
    id: '/api/public/admin/send-payment-confirmation',
    path: '/api/public/admin/send-payment-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAcceptOfferRoute =
  ApiPublicHooksAcceptOfferRouteImport.update({
    id: '/api/public/hooks/accept-offer',
    path: '/api/public/hooks/accept-offer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksConfirmManualRoute =
  ApiPublicHooksConfirmManualRouteImport.update({
    id: '/api/public/hooks/confirm-manual',
    path: '/api/public/hooks/confirm-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarkPaidRoute = ApiPublicHooksMarkPaidRouteImport.update({
  id: '/api/public/hooks/mark-paid',
  path: '/api/public/hooks/mark-paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendScheduledOffersRoute =
  ApiPublicHooksSendScheduledOffersRouteImport.update({
    id: '/api/public/hooks/send-scheduled-offers',
    path: '/api/public/hooks/send-scheduled-offers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrackRoute = ApiPublicHooksTrackRouteImport.update({
  id: '/api/public/hooks/track',
  path: '/api/public/hooks/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anwaelte': typeof AnwaelteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/angebot-anfordern/': typeof AngebotAnfordernIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/manuell': typeof AuthenticatedAdminManuellRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/beleg-print/$art/$token': typeof BelegPrintArtTokenRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/admin/send-invoice': typeof ApiPublicAdminSendInvoiceRoute
  '/api/public/admin/send-manual-invoice': typeof ApiPublicAdminSendManualInvoiceRoute
  '/api/public/admin/send-offer': typeof ApiPublicAdminSendOfferRoute
  '/api/public/admin/send-payment-confirmation': typeof ApiPublicAdminSendPaymentConfirmationRoute
  '/api/public/hooks/accept-offer': typeof ApiPublicHooksAcceptOfferRoute
  '/api/public/hooks/confirm-manual': typeof ApiPublicHooksConfirmManualRoute
  '/api/public/hooks/mark-paid': typeof ApiPublicHooksMarkPaidRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
  '/api/public/hooks/track': typeof ApiPublicHooksTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anwaelte': typeof AnwaelteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/angebot-anfordern': typeof AngebotAnfordernIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/admin/manuell': typeof AuthenticatedAdminManuellRoute
  '/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/beleg-print/$art/$token': typeof BelegPrintArtTokenRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/admin/send-invoice': typeof ApiPublicAdminSendInvoiceRoute
  '/api/public/admin/send-manual-invoice': typeof ApiPublicAdminSendManualInvoiceRoute
  '/api/public/admin/send-offer': typeof ApiPublicAdminSendOfferRoute
  '/api/public/admin/send-payment-confirmation': typeof ApiPublicAdminSendPaymentConfirmationRoute
  '/api/public/hooks/accept-offer': typeof ApiPublicHooksAcceptOfferRoute
  '/api/public/hooks/confirm-manual': typeof ApiPublicHooksConfirmManualRoute
  '/api/public/hooks/mark-paid': typeof ApiPublicHooksMarkPaidRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
  '/api/public/hooks/track': typeof ApiPublicHooksTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/anwaelte': typeof AnwaelteRoute
  '/auth': typeof AuthRoute
  '/datenschutz': typeof DatenschutzRoute
  '/fachgebiete': typeof FachgebieteRoute
  '/fileupload': typeof FileuploadRoute
  '/impressum': typeof ImpressumRoute
  '/kanzlei': typeof KanzleiRoute
  '/kontakt': typeof KontaktRoute
  '/rechnung': typeof RechnungRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/angebot-anfordern/danke': typeof AngebotAnfordernDankeRoute
  '/angebot-anfordern/': typeof AngebotAnfordernIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRoute
  '/_authenticated/admin/manuell': typeof AuthenticatedAdminManuellRoute
  '/_authenticated/admin/traffic': typeof AuthenticatedAdminTrafficRoute
  '/beleg-print/$art/$token': typeof BelegPrintArtTokenRoute
  '/juli/angebote/$filename': typeof JuliAngeboteFilenameRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/admin/send-invoice': typeof ApiPublicAdminSendInvoiceRoute
  '/api/public/admin/send-manual-invoice': typeof ApiPublicAdminSendManualInvoiceRoute
  '/api/public/admin/send-offer': typeof ApiPublicAdminSendOfferRoute
  '/api/public/admin/send-payment-confirmation': typeof ApiPublicAdminSendPaymentConfirmationRoute
  '/api/public/hooks/accept-offer': typeof ApiPublicHooksAcceptOfferRoute
  '/api/public/hooks/confirm-manual': typeof ApiPublicHooksConfirmManualRoute
  '/api/public/hooks/mark-paid': typeof ApiPublicHooksMarkPaidRoute
  '/api/public/hooks/send-scheduled-offers': typeof ApiPublicHooksSendScheduledOffersRoute
  '/api/public/hooks/track': typeof ApiPublicHooksTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anwaelte'
    | '/auth'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/admin'
    | '/angebot-anfordern/danke'
    | '/angebot-anfordern/'
    | '/admin/$id'
    | '/admin/einstellungen'
    | '/admin/manuell'
    | '/admin/traffic'
    | '/beleg-print/$art/$token'
    | '/juli/angebote/$filename'
    | '/admin/'
    | '/api/public/admin/send-invoice'
    | '/api/public/admin/send-manual-invoice'
    | '/api/public/admin/send-offer'
    | '/api/public/admin/send-payment-confirmation'
    | '/api/public/hooks/accept-offer'
    | '/api/public/hooks/confirm-manual'
    | '/api/public/hooks/mark-paid'
    | '/api/public/hooks/send-scheduled-offers'
    | '/api/public/hooks/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anwaelte'
    | '/auth'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/angebot-anfordern/danke'
    | '/angebot-anfordern'
    | '/admin/$id'
    | '/admin/einstellungen'
    | '/admin/manuell'
    | '/admin/traffic'
    | '/beleg-print/$art/$token'
    | '/juli/angebote/$filename'
    | '/admin'
    | '/api/public/admin/send-invoice'
    | '/api/public/admin/send-manual-invoice'
    | '/api/public/admin/send-offer'
    | '/api/public/admin/send-payment-confirmation'
    | '/api/public/hooks/accept-offer'
    | '/api/public/hooks/confirm-manual'
    | '/api/public/hooks/mark-paid'
    | '/api/public/hooks/send-scheduled-offers'
    | '/api/public/hooks/track'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anwaelte'
    | '/auth'
    | '/datenschutz'
    | '/fachgebiete'
    | '/fileupload'
    | '/impressum'
    | '/kanzlei'
    | '/kontakt'
    | '/rechnung'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/angebot-anfordern/danke'
    | '/angebot-anfordern/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/einstellungen'
    | '/_authenticated/admin/manuell'
    | '/_authenticated/admin/traffic'
    | '/beleg-print/$art/$token'
    | '/juli/angebote/$filename'
    | '/_authenticated/admin/'
    | '/api/public/admin/send-invoice'
    | '/api/public/admin/send-manual-invoice'
    | '/api/public/admin/send-offer'
    | '/api/public/admin/send-payment-confirmation'
    | '/api/public/hooks/accept-offer'
    | '/api/public/hooks/confirm-manual'
    | '/api/public/hooks/mark-paid'
    | '/api/public/hooks/send-scheduled-offers'
    | '/api/public/hooks/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnwaelteRoute: typeof AnwaelteRoute
  AuthRoute: typeof AuthRoute
  DatenschutzRoute: typeof DatenschutzRoute
  FachgebieteRoute: typeof FachgebieteRoute
  FileuploadRoute: typeof FileuploadRoute
  ImpressumRoute: typeof ImpressumRoute
  KanzleiRoute: typeof KanzleiRoute
  KontaktRoute: typeof KontaktRoute
  RechnungRoute: typeof RechnungRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AngebotAnfordernDankeRoute: typeof AngebotAnfordernDankeRoute
  AngebotAnfordernIndexRoute: typeof AngebotAnfordernIndexRoute
  BelegPrintArtTokenRoute: typeof BelegPrintArtTokenRoute
  JuliAngeboteFilenameRoute: typeof JuliAngeboteFilenameRoute
  ApiPublicAdminSendInvoiceRoute: typeof ApiPublicAdminSendInvoiceRoute
  ApiPublicAdminSendManualInvoiceRoute: typeof ApiPublicAdminSendManualInvoiceRoute
  ApiPublicAdminSendOfferRoute: typeof ApiPublicAdminSendOfferRoute
  ApiPublicAdminSendPaymentConfirmationRoute: typeof ApiPublicAdminSendPaymentConfirmationRoute
  ApiPublicHooksAcceptOfferRoute: typeof ApiPublicHooksAcceptOfferRoute
  ApiPublicHooksConfirmManualRoute: typeof ApiPublicHooksConfirmManualRoute
  ApiPublicHooksMarkPaidRoute: typeof ApiPublicHooksMarkPaidRoute
  ApiPublicHooksSendScheduledOffersRoute: typeof ApiPublicHooksSendScheduledOffersRoute
  ApiPublicHooksTrackRoute: typeof ApiPublicHooksTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anwaelte': {
      id: '/anwaelte'
      path: '/anwaelte'
      fullPath: '/anwaelte'
      preLoaderRoute: typeof AnwaelteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fachgebiete': {
      id: '/fachgebiete'
      path: '/fachgebiete'
      fullPath: '/fachgebiete'
      preLoaderRoute: typeof FachgebieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fileupload': {
      id: '/fileupload'
      path: '/fileupload'
      fullPath: '/fileupload'
      preLoaderRoute: typeof FileuploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanzlei': {
      id: '/kanzlei'
      path: '/kanzlei'
      fullPath: '/kanzlei'
      preLoaderRoute: typeof KanzleiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechnung': {
      id: '/rechnung'
      path: '/rechnung'
      fullPath: '/rechnung'
      preLoaderRoute: typeof RechnungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/angebot-anfordern/': {
      id: '/angebot-anfordern/'
      path: '/angebot-anfordern'
      fullPath: '/angebot-anfordern/'
      preLoaderRoute: typeof AngebotAnfordernIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebot-anfordern/danke': {
      id: '/angebot-anfordern/danke'
      path: '/angebot-anfordern/danke'
      fullPath: '/angebot-anfordern/danke'
      preLoaderRoute: typeof AngebotAnfordernDankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/einstellungen': {
      id: '/_authenticated/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manuell': {
      id: '/_authenticated/admin/manuell'
      path: '/manuell'
      fullPath: '/admin/manuell'
      preLoaderRoute: typeof AuthenticatedAdminManuellRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/traffic': {
      id: '/_authenticated/admin/traffic'
      path: '/traffic'
      fullPath: '/admin/traffic'
      preLoaderRoute: typeof AuthenticatedAdminTrafficRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/beleg-print/$art/$token': {
      id: '/beleg-print/$art/$token'
      path: '/beleg-print/$art/$token'
      fullPath: '/beleg-print/$art/$token'
      preLoaderRoute: typeof BelegPrintArtTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juli/angebote/$filename': {
      id: '/juli/angebote/$filename'
      path: '/juli/angebote/$filename'
      fullPath: '/juli/angebote/$filename'
      preLoaderRoute: typeof JuliAngeboteFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/send-invoice': {
      id: '/api/public/admin/send-invoice'
      path: '/api/public/admin/send-invoice'
      fullPath: '/api/public/admin/send-invoice'
      preLoaderRoute: typeof ApiPublicAdminSendInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/send-manual-invoice': {
      id: '/api/public/admin/send-manual-invoice'
      path: '/api/public/admin/send-manual-invoice'
      fullPath: '/api/public/admin/send-manual-invoice'
      preLoaderRoute: typeof ApiPublicAdminSendManualInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/send-offer': {
      id: '/api/public/admin/send-offer'
      path: '/api/public/admin/send-offer'
      fullPath: '/api/public/admin/send-offer'
      preLoaderRoute: typeof ApiPublicAdminSendOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/send-payment-confirmation': {
      id: '/api/public/admin/send-payment-confirmation'
      path: '/api/public/admin/send-payment-confirmation'
      fullPath: '/api/public/admin/send-payment-confirmation'
      preLoaderRoute: typeof ApiPublicAdminSendPaymentConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/accept-offer': {
      id: '/api/public/hooks/accept-offer'
      path: '/api/public/hooks/accept-offer'
      fullPath: '/api/public/hooks/accept-offer'
      preLoaderRoute: typeof ApiPublicHooksAcceptOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/confirm-manual': {
      id: '/api/public/hooks/confirm-manual'
      path: '/api/public/hooks/confirm-manual'
      fullPath: '/api/public/hooks/confirm-manual'
      preLoaderRoute: typeof ApiPublicHooksConfirmManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mark-paid': {
      id: '/api/public/hooks/mark-paid'
      path: '/api/public/hooks/mark-paid'
      fullPath: '/api/public/hooks/mark-paid'
      preLoaderRoute: typeof ApiPublicHooksMarkPaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-scheduled-offers': {
      id: '/api/public/hooks/send-scheduled-offers'
      path: '/api/public/hooks/send-scheduled-offers'
      fullPath: '/api/public/hooks/send-scheduled-offers'
      preLoaderRoute: typeof ApiPublicHooksSendScheduledOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/track': {
      id: '/api/public/hooks/track'
      path: '/api/public/hooks/track'
      fullPath: '/api/public/hooks/track'
      preLoaderRoute: typeof ApiPublicHooksTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminEinstellungenRoute: typeof AuthenticatedAdminEinstellungenRoute
  AuthenticatedAdminManuellRoute: typeof AuthenticatedAdminManuellRoute
  AuthenticatedAdminTrafficRoute: typeof AuthenticatedAdminTrafficRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminEinstellungenRoute: AuthenticatedAdminEinstellungenRoute,
  AuthenticatedAdminManuellRoute: AuthenticatedAdminManuellRoute,
  AuthenticatedAdminTrafficRoute: AuthenticatedAdminTrafficRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnwaelteRoute: AnwaelteRoute,
  AuthRoute: AuthRoute,
  DatenschutzRoute: DatenschutzRoute,
  FachgebieteRoute: FachgebieteRoute,
  FileuploadRoute: FileuploadRoute,
  ImpressumRoute: ImpressumRoute,
  KanzleiRoute: KanzleiRoute,
  KontaktRoute: KontaktRoute,
  RechnungRoute: RechnungRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AngebotAnfordernDankeRoute: AngebotAnfordernDankeRoute,
  AngebotAnfordernIndexRoute: AngebotAnfordernIndexRoute,
  BelegPrintArtTokenRoute: BelegPrintArtTokenRoute,
  JuliAngeboteFilenameRoute: JuliAngeboteFilenameRoute,
  ApiPublicAdminSendInvoiceRoute: ApiPublicAdminSendInvoiceRoute,
  ApiPublicAdminSendManualInvoiceRoute: ApiPublicAdminSendManualInvoiceRoute,
  ApiPublicAdminSendOfferRoute: ApiPublicAdminSendOfferRoute,
  ApiPublicAdminSendPaymentConfirmationRoute:
    ApiPublicAdminSendPaymentConfirmationRoute,
  ApiPublicHooksAcceptOfferRoute: ApiPublicHooksAcceptOfferRoute,
  ApiPublicHooksConfirmManualRoute: ApiPublicHooksConfirmManualRoute,
  ApiPublicHooksMarkPaidRoute: ApiPublicHooksMarkPaidRoute,
  ApiPublicHooksSendScheduledOffersRoute:
    ApiPublicHooksSendScheduledOffersRoute,
  ApiPublicHooksTrackRoute: ApiPublicHooksTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
